[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eyeball"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

[tool.setuptools]
packages = { find = { include = ["eyeball*"] } }

