_target_: eyeball.envs.launch.LaunchConfig

sensors:
  cameras:
    eye:
        _target_: eyeball.sensors.cameras.camera.CameraNode
        name: "eye"
        camera:
            _target_: eyeball.sensors.cameras.opencv_camera.OpencvCamera
            device_path: "/dev/video0"
            resolution: [640, 480]
            fps: 90
            camera_type: "usb_camera"

robots:
  left: ["robot_configs/eyeball.yaml"]

agent:
  _target_: eyeball.agents.teleoperation.viser_agent.ViserEyeballAgent
